services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family-desktop
    restart: unless-stopped
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge