version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    container_name: family-desktop-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network-dev
    command: bun run dev -- --host

networks:
  app-network-dev:
    driver: bridge